### ISSUE TITLE
feat: Support `alias` Options

### ISSUE THREAD

**Issue by shinGangan** [wattanx/nuxt-pandacss#33]
## Context

現在、`alias`オプションは`styled-system`固定値となっている。

- [src/module.ts#L54-L56](https://github.com/wattanx/nuxt-pandacss/blob/32da4d3a07ee37ccd6a83391725b9c1ebf99b395/src/module.ts#L54-L56)

outdir名を変更した場合、このalias設定が固有値なためimportで失敗する。
例えば、`outdir: .pandacss`に変更した場合などである。

そこでalias OptionsをNuxt Module Optionsとしてサポートする。

### Note

本PRと合わせて以下2点のrefactorも混ぜられたらと考えています(レビュー対応数の削減目的。目的ごとにPR分けた方がよければPR分けます。言及なければ混ぜてしまいますのでお気軽に指摘ください)　

- `from '@nuxt/kit'`からのimport
  - 73cb2e79c6de47937e88b443c38d581b0f5c13d0 対応時にミスっていました
  - https://github.com/wattanx/nuxt-pandacss/blob/main/src/resolvers.ts#L1
- `types.ts`ファイルの用意
  - 本PRのようにオプションが増えることを考慮して`types.ts`を用意
  - ディレクトリ構成などは[Nuxt Tailwind](https://github.com/nuxt-modules/tailwindcss/tree/8244bc0204b5c7bfbd57736122b81fa6abfaf887/src)からインスパイアを受けています

**Comment by shinGangan** [comment]
@wattanx 

お手隙の際に確認・レビューお願い致します。
対応方針に問題なければ、私の方で対応・PR作成を行います。

よろしくお願い致します🙇

**Comment by wattanx** [comment]
方針良さそうです！
変更が多くなるなら別PR。変更が少ないならコミット分けて同一PRに混ぜるくらいの感じで大丈夫です！

**Comment by shinGangan** [comment]
> 方針良さそうです！ 変更が多くなるなら別PR。変更が少ないならコミット分けて同一PRに混ぜるくらいの感じで大丈夫です！

承知ですー！

typesは変更範囲広いのでrefactor PR出します。
他にも普段利用していて気になった点があるので別途Issue立てます🙏
