### ISSUE TITLE
discuss: submit a Module Listing Request to `nuxt/module`

### ISSUE THREAD

**Issue by shinGangan** [wattanx/nuxt-pandacss#58]
### Context

[nuxi module add / search](https://nuxt.com/docs/api/commands/module) command can be used to search for and add modules.
`nuxi module add / search` command targets a set of modules added to [nuxt/modules/modules/*](https://github.com/nuxt/modules/tree/3a7873d00b2b062206744a59cfd3f92a4deae2c2/modules).

Do you plan to add to nuxi/module?

### my opinion

As for me, I would be happy to add `nuxt-pandacss` using `nuxi module` command.
If @wattanx  and I have no disagreement, I will draft a Module Listing Request Issue on my end.

**Comment by wattanx** [comment]
I will add it when I can release v1!

**Comment by shinGangan** [comment]
OK. I will continue to contribute to make it a good module.
